```sql
CREATE TABLE Autor (
  AutorID INT IDENTITY PRIMARY KEY,
  Jmeno NVARCHAR(100) NOT NULL,
  Prijmeni NVARCHAR(100) NOT NULL
);

CREATE TABLE Zanr (
  ZanrID INT IDENTITY PRIMARY KEY,
  Nazev NVARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Vydavatel (
  VydavatelID INT IDENTITY PRIMARY KEY,
  Nazev NVARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE Titul (
  TitulID INT IDENTITY PRIMARY KEY,
  Nazev NVARCHAR(200) NOT NULL,
  ISBN NVARCHAR(20) NULL UNIQUE,
  RokVydani SMALLINT NULL,
  Nosic NVARCHAR(30) NOT NULL,
  StrucnyObsah NVARCHAR(MAX) NULL,
  VydavatelID INT NOT NULL REFERENCES Vydavatel(VydavatelID)
);

CREATE TABLE Exemplar (
  ExemplarID INT IDENTITY PRIMARY KEY,
  TitulID INT NOT NULL REFERENCES Titul(TitulID),
  InventarniCislo NVARCHAR(30) NOT NULL UNIQUE,
  Stav NVARCHAR(20) NOT NULL DEFAULT 'Dostupný'
);

CREATE TABLE Ctenar (
  CtenarID INT IDENTITY PRIMARY KEY,
  CisloPrukazky NVARCHAR(20) NOT NULL UNIQUE,
  Jmeno NVARCHAR(100) NOT NULL,
  Prijmeni NVARCHAR(100) NOT NULL,
  DatumNarozeni DATE NULL,
  Pohlavi NCHAR(1) NULL,
  Vzdelani NVARCHAR(50) NULL,
  Aktivni BIT NOT NULL DEFAULT 1
);
